name: Docker Image CI

on:
  push:
    branches: '**'
    tags: '**'
  schedule:
  - cron: 0 0 * * 6

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_type: ["fpm", "apache"]
        php_version: ["5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images:
            enterprisedev/php-base
          flavor: |
            suffix=-${{ matrix.php_type }}-${{ matrix.php_version }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: ${{ (github.repository == 'enterprise-imm/php-base') && (github.ref == 'refs/heads/master') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-${{ matrix.php_type }}
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
          push: ${{ (github.repository == 'enterprise-imm/php-base') && (github.ref == 'refs/heads/master') }}
          build-args: |
            DOCK_PHP_VERSION=${{ matrix.php_version }}
            INSTALL_SOAP=true
            INSTALL_MYSQLI=true
            INSTALL_PHPREDIS=true
            INSTALL_PCNTL=true
            INSTALL_BCMATH=true
            INSTALL_EXIF=true
            INSTALL_INTL=true
            INSTALL_LDAP=true
            INSTALL_IMAGE_OPTIMIZERS=true
            INSTALL_IMAGEMAGICK=true
            INSTALL_YAML=true
            INSTALL_GETTEXT=true
            INSTALL_ADDITIONAL_LOCALES=true
            ADDITIONAL_LOCALES="en_US.UTF-8 it_IT.UTF-8"
          tags: ${{ steps.meta.outputs.tags }}
